poc_nextcloud.settings:
  type: config_object
  label: 'POC Nextcloud settings'
  mapping:
    nextcloud_url:
      type: string
      label: 'Url to the nextcloud instance.'
    nextcloud_user:
      type: string
      label: 'Username for nextcloud API requests.'
    nextcloud_pass:
      # @todo Think of a safer way to store the password.
      type: string
      label: 'Password for nextcloud API requests.'
