version: '2'

services:
  # See https://hub.docker.com/_/nextcloud.
  nextcloud_db_base:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_PASSWORD=nextpw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud_base:
    build:
      context: ./docker-image
      dockerfile: Dockerfile
    restart: always
    volumes:
      # Insert custom php configuration.
      - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      MYSQL_PASSWORD: nextpw
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: nextcloud_db
      # By providing user and password, Nextcloud will be fully installed.
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      PHP_IDE_CONFIG: "serverName=nextcloud"
